version: '2'
services:
  web:
    build: .
    working_dir: /go/src/web
    volumes:
      - .:/go/src/web
    environment:
      - PORT=8080
    command: go run main.go
    ports:
      - "8080:8080"