version: '2'
services:
  web:
    build: .
    working_dir: /go/src/web
    volumes:
      - ./web:/go/src/web
    links:
      - db
    command: go run main.go
    ports:
      - "8080:8080"
  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"